SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS conglomerate_test.databasechangelog;
DROP TABLE IF EXISTS conglomerate_test.databasechangeloglock;
DROP TABLE IF EXISTS conglomerate_test.documents;
DROP TABLE IF EXISTS conglomerate_test.events;
DROP TABLE IF EXISTS conglomerate_test.groupings;
DROP TABLE IF EXISTS conglomerate_test.messages;
DROP TABLE IF EXISTS conglomerate_test.reset_pins;
DROP TABLE IF EXISTS conglomerate_test.user_group_mappings;
DROP TABLE IF EXISTS conglomerate_test.users;
DROP TABLE IF EXISTS conglomerate_test.devices;
DROP TABLE IF EXISTS conglomerate_test.user_read_messages_mappings;
DROP TABLE IF EXISTS conglomerate_test.folders;
DROP TABLE IF EXISTS conglomerate_test.user_event_mappings;
SET FOREIGN_KEY_CHECKS = 1;